#!/bin/bash
# DECISIVE EXPERIMENT (2026-09-10): is 50.9% the draft, the mechanism, or a verify bug?
#
# Three things, in one GPU-serialized script (one serve at a time; CPU-only phases never
# hold the GPU):
#   (A) export today's trained draft (step_001200) into a dflash2 artifact
#   (B) EXACTNESS: speculative decode must reproduce the plain-decode text bit-for-bit
#       (with a correct verifier the sampled sequence is identical). Any text difference
#       -> the verify path is wrong, which is a correctness bug, not a tuning problem.
#   (C) ACCEPTANCE: old draft (Aug 26 artifact) vs new draft (step_001200), same prompts.
#
# Do NOT edit this file while it runs (bash re-reads by byte offset).
set -u
J=/mnt/c/Users/User/Documents/ziqinzhang
M=/home/user/models
PORT=8389
BIN=/home/user/ninfer-fusion/build/apps/ninfer-serve
BASE=$M/qwen3_8_27b_nvfp4.ninfer
# the draft-carrying artifact is the --src: the plain artifact has no dflash2/* objects
SRC=$M/qwen3_8_27b_nvfp4_dflash2.ninfer
OLD=$SRC
CKPT=$J/data/dflash2_ckpts/step_001200.pt
NEW=$M/qwen3_8_27b_nvfp4_dflash2_w9s1200.ninfer
MD=$J/_collab/M_df2_w9_draft.md
LOG=$J/dl/df2_w9_v2.log
MAXTOK=192
PROMPT_ZH='用三句话介绍杭州的地理与历史。'
PROMPT_NUM='1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,'

exec >> "$LOG" 2>&1
echo "=================================================================="
echo "=== df2 w9 decisive run  $(date '+%F %H:%M:%S') ==="
free -g | head -2
df -h /home | tail -1

kill_serve() {
  local pid
  for pid in $(pgrep -f ninfer-serve 2>/dev/null); do
    grep -qa ninfer-serve /proc/$pid/cmdline 2>/dev/null || continue
    echo "  killing serve pid=$pid"
    kill -TERM "$pid" 2>/dev/null
  done
  sleep 4
}

# ---------------------------------------------------------------- (A) export
if [ -f "$NEW" ]; then
  echo "[A] $NEW already exists ($(stat -c %s "$NEW") bytes) - skipping export"
else
  cd "$J/ninfer-fusion-repo" || { echo "[A] repo missing"; exit 3; }
  export PYTHONPATH="$J/ninfer-fusion-repo"
  echo "[A] dry-run"
  python3 tools/convert/qwen3_8_27b/patch_dflash2.py \
    --src "$SRC" --ckpt "$CKPT" --out "$NEW" --dry-run 2>&1 | tail -8
  echo "[A] real"
  python3 tools/convert/qwen3_8_27b/patch_dflash2.py \
    --src "$SRC" --ckpt "$CKPT" --out "$NEW" 2>&1 | tail -8
  ls -l "$NEW" 2>/dev/null | cut -c1-110
  echo "[A] verify"
  python3 tools/convert/qwen3_8_27b/verify_patch.py --src "$SRC" --out "$NEW" --ckpt "$CKPT" 2>&1 | tail -8
fi
[ -f "$NEW" ] || { echo "[A] EXPORT FAILED - stopping"; echo "DF2_W9_V2_DONE"; exit 4; }

# ---------------------------------------------------------- serve + requests
: > /tmp/w9v2_rows
: > /tmp/w9v2_texts

ask() {  # label artifact prompt -> writes text to /tmp/w9v2_text_<label>.txt
  local label=$1 art=$2 prompt=$3 log=$4
  curl -s -m 300 -X POST "http://127.0.0.1:$PORT/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d "$(printf '{"model":"qwen3.8-27b","messages":[{"role":"user","content":"%s"}],"max_tokens":%s,"temperature":0,"stream":false}' "$prompt" "$MAXTOK")" \
    > /tmp/w9v2_resp.json
  python3 - "$label" <<'PY'
import json, sys
lab = sys.argv[1]
try:
    d = json.load(open("/tmp/w9v2_resp.json"))
    m = d["choices"][0]["message"]["content"]
except Exception as e:
    print("  [%s] PARSE-FAIL %s" % (lab, e))
    m = ""
open("/tmp/w9v2_text_%s.txt" % lab, "w").write(m)
print("  [%s] text[%d]: %s" % (lab, len(m), m.replace("\n", " ")[:90]))
PY
  local line; line=$(grep -E 'done .*speculative=' "$log" | tail -1)
  echo "[$label] $(printf '%s' "$line" | grep -oE 'gen=[0-9]+|finish=[a-z_]+|speculative=[a-z0-9_]+ [0-9.]+tok/round \([0-9.]+%\)|decode=[0-9.]+tok/s' | tr '\n' ' ')"
  echo "$label|$(printf '%s' "$line" | grep -oE '[0-9.]+tok/round \([0-9.]+%\)' | tr -d ' ')|$(printf '%s' "$line" | grep -oE 'gen=[0-9]+' | cut -d= -f2)|$(printf '%s' "$line" | grep -oE 'finish=[a-z_]+' | cut -d= -f2)|$(printf '%s' "$line" | grep -oE 'decode=[0-9.]+tok/s' | cut -d= -f2)" >> /tmp/w9v2_rows
}

serve() {  # artifact spec-flag...
  local art=$1; shift
  local log=/home/user/w9v2_$(basename "$art" .ninfer)_$1.log
  kill_serve
  : > "$log"
  cd /home/user/ninfer-fusion/build || exit 1
  setsid nohup "$BIN" "$art" --port $PORT --max-context 8192 --no-cuda-graph "$@" \
    > "$log" 2>&1 < /dev/null &
  local ok=0
  for _i in $(seq 1 150); do
    sleep 2
    curl -s -m 2 "http://127.0.0.1:$PORT/health" 2>/dev/null | grep -q ok && { ok=1; break; }
    pgrep -f ninfer-serve >/dev/null || break
  done
  if [ $ok -ne 1 ]; then echo "[serve $art] FAILED"; tail -4 "$log"; echo "$art|SERVE_FAILED|-|-|-" >> /tmp/w9v2_rows; return 1; fi
  echo "$log"
}

echo
echo "=== (B) EXACTNESS: plain vs dflash2 must emit identical text ==="
l1=$(serve "$BASE") && ask plain_zh "$BASE" "$PROMPT_ZH" "$l1" && ask plain_num "$BASE" "$PROMPT_NUM" "$l1"
l2=$(serve "$OLD" --spec auto) && ask df2old_zh "$OLD" "$PROMPT_ZH" "$l2" && ask df2old_num "$OLD" "$PROMPT_NUM" "$l2"
for pair in zh num; do
  a=/tmp/w9v2_text_plain_$pair.txt; b=/tmp/w9v2_text_df2old_$pair.txt
  if [ -s "$a" ] && [ -s "$b" ]; then
    if cmp -s "$a" "$b"; then echo "[EXACT $pair] IDENTICAL ($(wc -c < "$a") bytes) -> verifier exact"
    else echo "[EXACT $pair] *** DIFFERENT *** -> verify bug"; diff <(fold -w60 "$a") <(fold -w60 "$b") | head -12; fi
  else
    echo "[EXACT $pair] cannot compare (missing text)"
  fi
done

echo
echo "=== (C) acceptance: old draft (Aug 26) vs new draft (step_001200) ==="
[ -n "${l2:-}" ] || l2=$(serve "$OLD" --spec auto)
ask df2old_zh2 "$OLD" "$PROMPT_ZH" "$l2"
ask df2old_num2 "$OLD" "$PROMPT_NUM" "$l2"
l3=$(serve "$NEW" --spec auto) && ask df2new_zh "$NEW" "$PROMPT_ZH" "$l3" && ask df2new_num "$NEW" "$PROMPT_NUM" "$l3"
for pair in zh num; do
  a=/tmp/w9v2_text_df2old_${pair}2.txt; b=/tmp/w9v2_text_df2new_$pair.txt
  if [ -s "$a" ] && [ -s "$b" ]; then
    cmp -s "$a" "$b" && echo "[DRAFT-DELTA $pair] texts identical" || echo "[DRAFT-DELTA $pair] texts differ (expected: draft quality changed)"
  fi
done
kill_serve

{
  echo
  echo "## 决定性实验 v2 ($(date '+%F %H:%M')) — 草稿归因 / 机制归因 / verify 正确性"
  echo
  echo "ckpt=\`$CKPT\` (step 1200) -> \`$(basename "$NEW")\`; 引擎=\`$BIN\` ($(stat -c %y "$BIN" | cut -c1-16))"
  echo
  echo "| run | accept | gen | finish | decode |"
  echo "|---|---|---|---|---|"
  while IFS='|' read -r a b c d e; do [ -n "$a" ] && echo "| $a | $b | $c | $d | $e |"; done < /tmp/w9v2_rows
  echo
  echo "exactness: plain vs dflash2 文本比对见上（IDENTICAL -> verifier 精确；DIFFERENT -> verify bug）"
} >> "$MD"
cat /tmp/w9v2_rows
echo "DF2_W9_V2_DONE"
