#!/bin/bash
# Window H (v2) — ONE batch, ONE build, ONE verification round.
#
# v2 fixes three defects of the v1 run (2026-09-10, all in the harness, not the
# engine):
#   * `.patch` files were fed to `bash -n` and reported as broken scripts;
#   * stacked patches (s30 needs n1+n1b first) were dry-run against a PRISTINE
#     tree, so they could never pass — dry-runs now run sequentially in a
#     SHADOW copy, so each patch sees its prerequisites;
#   * the U7 diff was hand-written and malformed — now generated by
#     `_u7_mkpatch.py` and validated (`U7_PATCH_DRYRUN_OK`).
# Also adds SKIP_BASELINE=1 to skip the GPU baseline step when the question it
# answers has moved on.
#
# Order: [baseline] -> dry-run+apply -> ONE build (ccache) -> judgements ->
#        resume W9 training LAST (user's ordering, 2026-09-10).
set -u
J=/mnt/c/Users/User/Documents/ziqinzhang
R=/home/user/ninfer-fusion
LOG=$J/dl/window_h.log
: > "$LOG"
exec >> "$LOG" 2>&1
export NVCC_PREPEND_FLAGS="--split-compile-extended=8"
SKIP_L3=${SKIP_L3:-0}; SKIP_L2=${SKIP_L2:-0}; SKIP_BASELINE=${SKIP_BASELINE:-0}
echo "=== window H v2 start $(date +%F' '%H:%M:%S) ===  SKIP_L3=$SKIP_L3 SKIP_L2=$SKIP_L2 SKIP_BASELINE=$SKIP_BASELINE"
free -g | head -2
pgrep -af 'make|nvcc|ptxas|train_dflash2' | grep -v $$ || true
if pgrep -af train_dflash2 | grep -v $$ > /dev/null; then
  echo "ABORT: training is alive — pause it deliberately first"; echo WINDH_FAIL; exit 3
fi

if [ "$SKIP_BASELINE" = 0 ]; then
  echo "--- [1/6] U7 baseline (pre-fix evidence) $(date +%H:%M:%S) ---"
  bash "$J/_e8_muse_check.sh" || echo "(baseline returned non-zero; verdict line is the evidence)"
else
  echo "--- [1/6] baseline SKIPPED by request $(date +%H:%M:%S) ---"
fi

echo "--- [2/6] dry-runs in a shadow tree, sequential $(date +%H:%M:%S) ---"
cd "$R" || { echo WINDH_FAIL; exit 3; }
REQUIRED=()
[ "$SKIP_L3" = 0 ] && REQUIRED+=(s23_tu_split)
REQUIRED+=(n1_budget u7_muse_pagefill)
OPTIONAL=(n1b_cold_pages s30_budget_cold s24_window_table s28_rowscale_loader s31_503_p0 \
          s34_cold_loop s32_w13_p0 s35_frontload s38_calib_capture)
ORDER=("${REQUIRED[@]}" "${OPTIONAL[@]}")
declare -A PATCHES=()
[ "$SKIP_L3" = 0 ] && PATCHES[s23_tu_split]="$J/_collab/C_s23_tu_split/apply.sh"
PATCHES[n1_budget]="$J/_collab/A_n1_patch.diff"
PATCHES[n1b_cold_pages]="$J/_collab/A_n1b_cold_pages.diff"
PATCHES[s30_budget_cold]="$J/_collab/A_s30_budget_cold.diff"   # needs n1+n1b first
PATCHES[u7_muse_pagefill]="$J/_collab/M_muse_pagefill_patch.diff"
PATCHES[s24_window_table]="$J/_collab/A_s24_window_table.diff"
PATCHES[s28_rowscale_loader]="$J/_collab/C_s28_rowscale/patch/C_s28_loader.patch"
PATCHES[s31_503_p0]="$J/_collab/D_s31_503_p0.diff"
PATCHES[s34_cold_loop]="$J/_collab/C_s34_cold_loop/patch/C_s34_first_patch.diff"
PATCHES[s32_w13_p0]="$J/_collab/A_s32_w13_p0.diff"
PATCHES[s35_frontload]="$J/_collab/D_s35_frontload.diff"
PATCHES[s38_calib_capture]="$J/_collab/C_s38_calib/patch/C_s38_capture.diff"

SHADOW=$(mktemp -d /tmp/winh_shadow.XXXXXX)
cp -a "$R/src" "$SHADOW/" 2>/dev/null
[ -d "$R/include" ] && cp -a "$R/include" "$SHADOW/"
[ -f "$R/CMakeLists.txt" ] && cp -a "$R/CMakeLists.txt" "$SHADOW/"
echo "shadow tree: $SHADOW"
ok=1
for name in "${ORDER[@]}"; do
  p="${PATCHES[$name]:-}"
  required=0; for r in "${REQUIRED[@]}"; do [ "$r" = "$name" ] && required=1; done
  if [ -z "$p" ] || [ ! -e "$p" ]; then
    if [ "$required" = 1 ]; then echo "  MISSING (required) $name -> $p"; ok=0; else echo "  skip (absent) $name"; fi
    continue
  fi
  case "$p" in
    *.diff|*.patch)
      if patch -p1 --dry-run -d "$SHADOW" < "$p" > /tmp/dryrun_$name.log 2>&1 \
         && patch -p1 -d "$SHADOW" < "$p" >> /tmp/dryrun_$name.log 2>&1; then
        echo "  DRYRUN OK   $name (applied to shadow)"
      else
        echo "  DRYRUN FAIL $name"; tail -4 /tmp/dryrun_$name.log
        if [ "$required" = 1 ]; then ok=0; else echo "  (optional, skipped)"; PATCHES[$name]=""; fi
      fi ;;
    *.sh)
      if bash "$p" --dry-run > /tmp/dryrun_$name.log 2>&1 || bash -n "$p" >> /tmp/dryrun_$name.log 2>&1; then
        echo "  SCRIPT OK   $name"
      else
        echo "  SCRIPT FAIL $name"; tail -4 /tmp/dryrun_$name.log; ok=0
      fi ;;
    *) echo "  UNKNOWN KIND $name -> $p"; ok=0 ;;
  esac
done
if [ "$ok" != 1 ]; then
  echo "BATCH ABORT: a required patch is missing or does not apply — 不半途应用"; echo WINDH_FAIL; exit 3
fi
echo "--- [3/6] snapshot src/ $(date +%H:%M:%S) ---"
tar czf /tmp/pre_h_src.tgz -C "$R" src CMakeLists.txt 2>/dev/null && echo "snapshot /tmp/pre_h_src.tgz ready"

echo "--- [4/6] apply to the live tree $(date +%H:%M:%S) ---"
if [ "$SKIP_L3" = 0 ]; then bash "${PATCHES[s23_tu_split]}" && echo "applied s23_tu_split"; fi
for name in n1_budget n1b_cold_pages s30_budget_cold u7_muse_pagefill s24_window_table \
            s28_rowscale_loader s31_503_p0 s34_cold_loop s32_w13_p0 s35_frontload \
            s38_calib_capture; do
  p="${PATCHES[$name]:-}"
  [ -z "$p" ] || [ ! -e "$p" ] && continue
  patch -p1 -d "$R" < "$p" && echo "applied $name"
done
if [ "$SKIP_L2" = 0 ]; then
  cd "$R/build" || { echo WINDH_FAIL; exit 3; }
  cmake -DCMAKE_CUDA_COMPILER_LAUNCHER=ccache . >> "$LOG" 2>&1 \
    && echo "ccache launcher set (expect a FULL CUDA rebuild: .o depends on flags.make)"
fi

echo "--- [5/6] ONE build $(date +%H:%M:%S) ---"
cd "$R/build" || { echo WINDH_FAIL; exit 3; }
JOBS=1; [ "$SKIP_L3" = 0 ] && JOBS=2
BIN=apps/ninfer
before=$(stat -c %Y "$BIN")
rm -f src/CMakeFiles/ninfer_ops.dir/ops/launcher/gqa_attention_decode.cu.o \
      src/CMakeFiles/ninfer_ops.dir/ops/launcher/gqa_attention_decode_e8.cu.o
rc=1
for attempt in 1 2 3 4; do
  echo "--- make ninfer -j$JOBS attempt $attempt $(date +%H:%M:%S) ---"
  free -g | sed -n 2p
  make ninfer -j"$JOBS" > /tmp/wh_make.log 2>&1
  rc=$?
  tail -6 /tmp/wh_make.log
  [ $rc -eq 0 ] && break
  echo "attempt $attempt failed rc=$rc; retry (resumes from built .o)"
  sleep 5
done
[ $rc -eq 0 ] || { echo "MAKE_FAILED rc=$rc — 不验证"; echo WINDH_FAIL; exit 3; }
after=$(stat -c %Y "$BIN")
if [ "$after" -le "$before" ]; then echo "RELINK_MISSING — 不验证"; echo WINDH_FAIL; exit 3; fi
echo "REBUILT OK ($before -> $after)"

echo "--- [6/6] judgements $(date +%H:%M:%S) ---"
echo "[6a] muse"; bash "$J/_muse_verify.sh"
echo "[6b] e8 three tiers (args fixed — the e8 configs had never actually run)"; bash "$J/_e8_postfix.sh"
echo "[6c] U7 re-check"; bash "$J/_e8_muse_check.sh"

echo "--- resume W9 training LAST $(date +%H:%M:%S) ---"
cd "$J" || { echo WINDH_FAIL; exit 3; }
powershell.exe -NoProfile -Command "Start-Process -FilePath 'cmd.exe' -ArgumentList '/c','C:\Users\User\Documents\ziqinzhang\_train_df2_resume.bat' -WindowStyle Hidden"
sleep 60
powershell.exe -NoProfile -Command "Get-CimInstance Win32_Process -Filter \"Name='python.exe'\" | Where-Object { \$_.CommandLine -like '*train_dflash2*' } | ForEach-Object { Write-Output ('resumed pid ' + \$_.ProcessId) }"
echo "revert if needed: tar xzf /tmp/pre_h_src.tgz -C $R"
echo "=== window H v2 done $(date +%F' '%H:%M:%S) ==="
echo WINDH_DONE
