// PLE n-gram row-derivation selftest.
//
// Two independent implementations are cross-checked:
//   * tools/ple_reference.py - the reference formula, written directly from
//     llama.cpp qwen4exp.cpp (PR #27742) in Python with explicit uint64
//     masking, so it cannot share a bug with the C++ code under test.
//   * ninfer::ops::ple::PleLayout::derive_rows - the code under test.
//
// The fixture (synthetic 32k-row sidecar) is generated by the same script,
// so this test exercises manifest parsing, row location, and row derivation
// end to end without downloading the 95 GiB production table.

#include "ops/ple/ple_layout.h"
#include "ops/ple/ple_table.h"

#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include <array>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

const char* kReference = NINFER_SOURCE_DIR "/tools/ple_reference.py";
constexpr int kTokens[] = {5, 7, 7, 9, 9, 9, 100, 200, 300};
constexpr int kEos = 151643;
constexpr int kNTokens = 9;
constexpr int kHeads = 16;

std::string run_python(const std::string& args) {
    std::string cmd = std::string(NINFER_PYTHON_EXECUTABLE) + " " + kReference + " " + args;
    std::string out;
    std::array<char, 256> buf{};
    FILE* pipe = popen(cmd.c_str(), "r");
    if (!pipe) { return {}; }
    while (fgets(buf.data(), static_cast<int>(buf.size()), pipe)) { out += buf.data(); }
    pclose(pipe);
    return out;
}

bool parse_rows(const std::string& text, std::vector<std::array<int, kHeads>>& rows) {
    std::istringstream in(text);
    std::string line;
    while (std::getline(in, line)) {
        std::istringstream ls(line);
        int tok = 0;
        char open = 0, comma = 0, close = 0;
        ls >> tok >> open;
        if (open != '[') { return false; }
        std::array<int, kHeads> row{};
        for (int h = 0; h < kHeads; ++h) {
            int v = 0;
            ls >> v >> comma;
            row[h] = v;
        }
        rows.push_back(row);
    }
    return rows.size() == kNTokens;
}

int expect_fail(const std::string& what, const std::string& detail) {
    std::fprintf(stderr, "FAIL: %s\n%s\n", what.c_str(), detail.c_str());
    return 1;
}

} // namespace

int main(int argc, char** argv) {
    std::filesystem::path fixture;
    if (argc > 1) {
        fixture = argv[1];
    } else {
        fixture = std::filesystem::temp_directory_path() / "ple_selftest_fixture";
    }

    // 1. Generate the synthetic sidecar with the reference script.
    const std::string gen_out = run_python("gen \"" + fixture.string() + "\"");
    if (gen_out.empty()) {
        return expect_fail("python fixture generation produced no output",
                           "check NINFER_PYTHON_EXECUTABLE and tools/ple_reference.py");
    }

    // 2. Reference rows.
    std::vector<std::array<int, kHeads>> expected;
    const std::string ref_out = run_python("derive \"" + fixture.string() + "/ple-manifest.json\"");
    if (!parse_rows(ref_out, expected)) {
        return expect_fail("reference derivation", ref_out);
    }

    // 3. C++ layout under test.
    ninfer::ops::ple::PleLayout layout;
    try {
        layout = ninfer::ops::ple::PleLayout::from_manifest(
            (fixture / "ple-manifest.json").string());
    } catch (const std::exception& e) {
        return expect_fail("manifest parse", e.what());
    }
    if (layout.ngram_size != 3 || layout.n_heads != kHeads) {
        return expect_fail("layout geometry", "ngram/heads mismatch");
    }

    // 4. Derive with the C++ implementation and compare. The fixture is a
    //    sequence-start window, so every predecessor is EOS (missing).
    std::vector<int32_t> prevs(kNTokens * 2, kEos);
    std::array<int, kHeads * kNTokens> rows{};
    layout.derive_rows(std::span<const int32_t>(kTokens, kNTokens),
                       std::span<const int32_t>(prevs), kEos, rows.data());
    for (int i = 0; i < kNTokens; ++i) {
        for (int h = 0; h < kHeads; ++h) {
            if (rows[i * kHeads + h] != expected[i][h]) {
                std::string detail = "token " + std::to_string(i) + " head " +
                                     std::to_string(h) + ": C++ " +
                                     std::to_string(rows[i * kHeads + h]) +
                                     " != reference " + std::to_string(expected[i][h]);
                return expect_fail("row derivation", detail);
            }
        }
    }
    std::printf("PLE layout row derivation matches the llama.cpp reference (%d tokens x %d heads)\n",
                kNTokens, kHeads);

    // 5. Device-side gather: rows were written as their own row id, so the
    //    gathered halves must equal the derived row ids.
    ninfer::ops::ple::PleTableOptions opts;
    opts.sidecar_root = fixture;
    opts.cache_bytes = 8ULL << 20;
    ninfer::ops::ple::PleTable table(opts);

    std::vector<int32_t> device_rows(rows.begin(), rows.end());
    const int row_dim = static_cast<int>(layout.embedding_row_dimension);
    __half* dst = nullptr;
    cudaMalloc(&dst, kNTokens * kHeads * row_dim * sizeof(__half));
    cudaStream_t stream = nullptr;
    cudaStreamCreate(&stream);
    table.gather(device_rows.data(), kNTokens, dst, stream);
    cudaStreamSynchronize(stream);
    cudaStreamDestroy(stream);

    std::vector<__half> dst_host(kNTokens * kHeads * row_dim);
    cudaMemcpy(dst_host.data(), dst, dst_host.size() * sizeof(__half), cudaMemcpyDeviceToHost);
    cudaFree(dst);

    for (int i = 0; i < kNTokens; ++i) {
        for (int h = 0; h < kHeads; ++h) {
            const __half v = dst_host[i * kHeads * row_dim + h * row_dim];
            const unsigned bits = *reinterpret_cast<const unsigned*>(&v) & 0xFFFF;
            if (bits != static_cast<unsigned>(rows[i * kHeads + h])) {
                std::string detail = "token " + std::to_string(i) + " head " +
                                     std::to_string(h) + ": gathered " +
                                     std::to_string(bits) + " != row " +
                                     std::to_string(rows[i * kHeads + h]);
                return expect_fail("UVA gather round-trip", detail);
            }
        }
    }
    std::printf("PLE UVA gather round-trip OK (%d rows through pinned cache)\n",
                kNTokens * kHeads);
    return 0;
}
