// GENERATED by tools/archkit/kit/scaffold.py -- DO NOT EDIT BY HAND.
//
// Source: tools/archkit/specs/minicpm5_1b_spec.json
// Marker: ARCHKIT_SCAFFOLD_MINICPM5_1B_POST_176d84cb9458f80d
//
// This file is the MECHANICAL half only.  It states the geometry the spec
// declares and the invariants that bind it, so that the hand-written
// `config.h` next door cannot disagree with the spec in silence.  It does
// NOT declare the family accessors, the per-layer tables, or the knobs --
// see the FORBIDDEN list in kit/scaffold.py for why, and the TODO(hand)
// block at the bottom of this file for what is left to a human.

#ifndef NINFER_TARGETS_MINICPM5_1B_IMPL_SPEC_CONTRACT_H
#define NINFER_TARGETS_MINICPM5_1B_IMPL_SPEC_CONTRACT_H

#include <cstdint>

namespace ninfer::targets::minicpm5_1b::detail::spec_contract {

// A string literal, not a macro: it survives preprocessing and reaches the
// object file, so the compile gate can show that the TU it compiled included
// THIS copy of the header and not another one on the include path (R52).
inline constexpr const char* kScaffoldMarker = "ARCHKIT_SCAFFOLD_MINICPM5_1B_POST_176d84cb9458f80d";
inline constexpr const char* kSpecModelId = "minicpm5-1b";
inline constexpr const char* kHfArchitecture = "LlamaForCausalLM";

// ---- geometry, copied from the spec -------------------------------
inline constexpr int hidden       = 1536;
inline constexpr int layers       = 24;
inline constexpr int query_heads  = 16;
inline constexpr int kv_heads     = 2;
inline constexpr int head_dim     = 128;
inline constexpr int vocab        = 130560;
inline constexpr int max_ctx      = 131072;
inline constexpr int intermediate = 4608;
inline constexpr double rms_eps     = 1e-06;
inline constexpr float rope_theta  = 5000000.0F;

// ---- derived, and asserted so the derivation is not a hope --------
inline constexpr int query_size = query_heads * head_dim;
inline constexpr int kv_size    = kv_heads * head_dim;

// ---- the layer schedule, as three counts and one sum --------------
inline constexpr int full_layers    = 24;
inline constexpr int sliding_layers = 0;
inline constexpr int gdn_layers     = 0;
inline constexpr int schedule_total = full_layers + sliding_layers + gdn_layers;

static_assert(schedule_total == layers,
    "THE ADAPT.PY DEFECT, AS A COMPILE ERROR: the layer schedule does not cover "
    "every layer.  A generated config.h for spark reported 9 full + 0 gdn on a "
    "36-layer stack; nine plus zero is nine, so 27 layers would never execute "
    "and nothing would have failed.  Fix the spec, not this assert.");
static_assert(head_dim == 128 || head_dim == 256,
    "the shared GQA kernel domain is head_dim in {128, 256} (src/ops/kernel/ "
    "gqa_attention_geometry.cuh:16 is the static_assert this mirrors); a model "
    "outside it is a different kernel, not a table row.");
static_assert(query_size % 128 == 0 && kv_size % 128 == 0,
    "query/kv width must be a whole number of 128-row blocks.");
static_assert(vocab > 0 && intermediate > 0 && hidden > 0,
    "geometry must be positive; a zero here means the spec extraction found no "
    "keys and copied defaults.");
// ---- TODO(hand): what this file must NOT decide --------------------
//
// 1. `TextConfig`: the family's struct, its slots and its accessors.  548 hand
//    lines for spark, with about 20 static_asserts of the OBSTACLE (see
//    src/targets/gemma4_31b/impl/config.h:197-268 for the shape of that).
// 2. the per-layer tables: layer_kind, layer_rope_theta, layer_rotary_dim,
//    kFullLayers.  Their contents are the model's semantics.
// 3. every family hook that kit/refcount.py reports as ZERO-REFERENCE: the
//    runtime does not read it today, so declaring it changes nothing and
//    relying on it changes nothing either.
// 4. output_rows / token_domain, which are the CHECKPOINT's tokenizer domain
//    and the artifact's padded row count -- a property of the head layout, not
//    of the spec's geometry.

}  // namespace ninfer::targets::minicpm5_1b::detail::spec_contract

#endif
