// GENERATED by tools/archkit/kit/scaffold.py -- the translation unit the
// compile gate compiles (kit/compilegate.sh).  It exists so that the
// mechanical contract is COMPILED and not merely written: a static_assert
// that nobody instantiates is a comment.
//
// Marker: ARCHKIT_SCAFFOLD_MINICPM5_1B_POST_176d84cb9458f80d

#include "impl/spec_contract.h"

extern "C" const char* ninfer_minicpm5_1b_scaffold_marker() {
    return ninfer::targets::minicpm5_1b::detail::spec_contract::kScaffoldMarker;
}

extern "C" int ninfer_minicpm5_1b_scaffold_schedule_total() {
    return ninfer::targets::minicpm5_1b::detail::spec_contract::schedule_total;
}
