// Generated by tools/archkit/gen_full_target.py  (DO NOT EDIT BY HAND).
// spec: muse-glimmer-30b
// 完整 TextConfig: 27b 同形访问器表面 + 逐层 kind/theta 表 (纯 softmax 族, gdn=0).
#pragma once

#include <array>
#include <cstdint>
#include <ninfer/targets/qwen3_6/hybrid_topology.h>
#include <ninfer/targets/qwen3_6/vision.h>

namespace ninfer::targets::muse_glimmer_30b::detail {

struct TextConfig {
    static constexpr int hidden       = 6656;
    static constexpr int layers       = 52;
    static constexpr int intermediate = 19968;

    // 输出行 (NVFP4 block-scale 布局要求 N%128==0) 与采样域分开:
    // artifact 行 = 202112 (含 64 零行), 采样域 = 202048 (真 vocab).
    static constexpr int output_rows  = 202112;
    static constexpr int token_domain = 202048;

    // 纯 softmax 族: 无 GDN/卷积/MTP. 槽位保留 0 (共享 ModelConfig 表面).
    static constexpr int gdn_conv_kernel      = 2;
    static constexpr int gdn_conv_state_width = 1;
    static constexpr int gdn_key_heads        = 1;
    static constexpr int gdn_key_head_dim     = 128;
    static constexpr int gdn_value_heads      = 1;
    static constexpr int gdn_value_head_dim   = 128;

    static constexpr int query_heads = 32;
    static constexpr int kv_heads    = 2;
    static constexpr int head_dim    = 128;
    static constexpr int rotary_dim  = 128;

    static constexpr float rms_epsilon      = 1e-05F;
    static constexpr float post_norm_eps    = 1e-08F;
    static constexpr float rope_theta       = 500000.0F;

    // 架构旋钮 (自动适配, 参考实现推导语义).
    static constexpr int   sliding_window        = 2048;
    static constexpr float qk_scale_factor       = 3.87F;
    static constexpr float final_logit_softcapping = 20.0F;

    static constexpr int key_dim               = gdn_key_heads * gdn_key_head_dim;
    static constexpr int value_dim             = gdn_value_heads * gdn_value_head_dim;
    static constexpr int convolution_dim       = 2 * key_dim + value_dim;
    static constexpr int query_size            = query_heads * head_dim;
    static constexpr int kv_size               = kv_heads * head_dim;
    static constexpr int query_projection_rows = 2 * query_size;

    static constexpr int mtp_layers               = 0;
    static constexpr int mtp_input_rows           = 0;
    static constexpr int mtp_attention_input_rows = 0;
    static constexpr int mtp_mlp_gate_up_rows     = 0;

    // 逐层口味表: 0 = full, 1 = swa (sliding window). 全部层均为 softmax 注意力;
    // gdn 层数为 0 -> 共享 run_layers 的 gdn 分支恒不进入.
    static constexpr std::array<int, 52> layer_kind{1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0};
    // 逐层 rope theta; 0 = NoPE (整层无位置编码, 引用推导语义:
    //   position_embeddings if layer_rope_theta[i] else None).
    static constexpr std::array<float, 52> layer_rope_theta{500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F};
    static constexpr std::array<int, 52> kFullLayers{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51};

    [[nodiscard]] static constexpr bool is_full_attention(int layer) {
        // Muse: 全部 52 层都是 softmax 注意力 (13 full + 39 sliding)。验收阶段
        // 39 个 sliding 层按 full 运行 (短上下文 < 窗口 2048 时窗口不裁剪, 与
        // HF 数值一致); E3 窗口接线后按 layer_kind 恢复窗口语义。
        return layer_kind[static_cast<std::size_t>(layer)] != 2;
    }
    [[nodiscard]] static constexpr bool is_swa_attention(int layer) {
        return layer_kind[static_cast<std::size_t>(layer)] == 1;
    }
    [[nodiscard]] static constexpr bool qk_norm_enabled() { return true; }
    [[nodiscard]] static constexpr bool per_layer_scalar() { return false; }
    [[nodiscard]] static constexpr bool final_logit_softcapping_enabled() {
        return final_logit_softcapping > 0.0F;
    }
    [[nodiscard]] static constexpr float output_multiplier() { return 0.19611613513818404F; }
    [[nodiscard]] static constexpr int full_attention_layers() { return 52; }
    [[nodiscard]] static constexpr int swa_attention_layers() { return 39; }
    [[nodiscard]] static constexpr int gdn_layers() { return 0; }
    [[nodiscard]] static constexpr int swa_attention_index(int layer) {
        int n = 0;
        for (int i = 0; i < layer; ++i) { n += is_swa_attention(i) ? 1 : 0; }
        return n;
    }
    [[nodiscard]] static constexpr int full_attention_index(int layer) {
        int n = 0;
        for (int i = 0; i < layer; ++i) { n += is_full_attention(i) ? 1 : 0; }
        return n;
    }
    [[nodiscard]] static constexpr int gdn_index(int) { return 0; }
    [[nodiscard]] static constexpr int layer_of_full_index(int fidx) {
        return kFullLayers[static_cast<std::size_t>(fidx)];
    }
    [[nodiscard]] static constexpr float rope_theta_at(int layer) {
        return layer_rope_theta[static_cast<std::size_t>(layer)];
    }
};

static_assert(TextConfig::full_attention_layers() == 52);
static_assert(TextConfig::swa_attention_layers() == 39);
static_assert(TextConfig::gdn_layers() == 0);
static_assert(TextConfig::layer_kind.size() == 52);
static_assert(TextConfig::layer_rope_theta.size() == 52);
// full 层位 bijection: layer_of_full_index(fidx) 逐一命中 full.
static_assert([] {
    for (int f = 0; f < TextConfig::full_attention_layers(); ++f) {
        if (!TextConfig::is_full_attention(TextConfig::layer_of_full_index(f))) {
            return false;
        }
    }
    return true;
}());
// NoPE 语义门: theta==0 的层不施加 rope (E1 逐层驱动); 验收阶段全层 full,
// theta==0 的 13 层仍为 NoPE (与 HF 一致)。
static_assert([] {
    int no_pe = 0;
    for (int l = 0; l < TextConfig::layers; ++l) {
        if (TextConfig::rope_theta_at(l) == 0.0F) { ++no_pe; }
    }
    return no_pe == 13;
}());

inline constexpr float kAttentionScale = 0.34206290539899237F;
inline constexpr float kGdnScale = 0.0F;
inline constexpr std::uint32_t kPrefillChunkAlignment = 128;
inline constexpr std::uint32_t kMaximumMtpDraftTokens = 5;
inline constexpr std::uint32_t kMaximumDFlashDraftTokens = 7;
inline constexpr std::uint32_t kNativeContext = 131072;

// 草稿后端占位: Muse 无 MTP/dflash/dflash2 (family 运行时表面保留, 0 层).
struct DFlashConfig {
    static constexpr bool supported     = false;
    static constexpr bool bf16_weights  = false;
    static constexpr int layers         = 0;
    static constexpr bool full_only     = true;
    static constexpr int local_layers   = 0;
    static constexpr int full_layers    = 0;
    static constexpr int feature_layers = 0;
    static constexpr int feature_rows   = 0;
    static constexpr int hidden         = TextConfig::hidden;
    static constexpr int intermediate   = TextConfig::intermediate;
    static constexpr int query_heads    = 0;
    static constexpr int kv_heads       = 0;
    static constexpr int head_dim       = 0;
    static constexpr int query_size     = 0;
    static constexpr int kv_size        = 0;
    static constexpr int local_capacity = 0;
    static constexpr std::uint32_t local_window = 0;
    static constexpr int mask_token     = 0;
    static constexpr float rms_epsilon  = TextConfig::rms_epsilon;
    static constexpr float rope_theta   = TextConfig::rope_theta;
    static constexpr float attention_scale = 0.0F;
    static constexpr float svip_entropy_threshold = 0.0F;
    static constexpr std::array<int, 1> target_feature_layers{0};
};

struct DFlash2Config {
    static constexpr bool supported     = false;
    static constexpr bool bf16_weights  = false;
    static constexpr int layers         = 0;
    static constexpr bool full_only     = true;
    static constexpr int local_layers   = 0;
    static constexpr int full_layers    = 0;
    static constexpr int feature_layers = 0;
    static constexpr int feature_rows   = 0;
    static constexpr int hidden         = TextConfig::hidden;
    static constexpr int intermediate   = TextConfig::intermediate;
    static constexpr int query_heads    = 0;
    static constexpr int kv_heads       = 0;
    static constexpr int head_dim       = 0;
    static constexpr int query_size     = 0;
    static constexpr int kv_size        = 0;
    static constexpr int local_capacity = 0;
    static constexpr std::uint32_t local_window = 0;
    static constexpr int mask_token     = 0;
    static constexpr float rms_epsilon  = TextConfig::rms_epsilon;
    static constexpr float rope_theta   = TextConfig::rope_theta;
    static constexpr float attention_scale = 0.0F;
    static constexpr int block_drafts   = 0;
    static constexpr int conv_group_size = 0;
    static constexpr int conv_kernel_size = 0;
    static constexpr int selector_rank   = 0;
    static constexpr int selector_top_k  = 0;
    // Rows of the checkpoint's dedicated proposal head (`text/draft_head`). Its
    // rows are shortlist entries: only the global ids reached through
    // `text/draft_head_token_ids` may index the selector codebooks (contract 6.1).
    static constexpr int draft_head_rows = 131072;
    static constexpr std::array<int, 1> target_feature_layers{0};
};

// 视觉占位: Muse 多模态为 new_op, 文本先行; 派生共享骨架以通过
// vision_context 的编译期成员访问 (features.vision=false 时永不实例化运行).
struct VisionConfig : qwen3_6::VisionBackboneConfig {
    static constexpr int output_hidden = TextConfig::hidden;
};

} // namespace ninfer::targets::muse_glimmer_30b::detail
