// Generated by tools/archkit/gen_full_target.py  (DO NOT EDIT BY HAND).
// spec: muse-glimmer-30b
// 完整 TextConfig: 27b 同形访问器表面 + 逐层 kind/theta 表 (纯 softmax 族, gdn=0).
#pragma once

#include <array>
#include <cstdint>

namespace ninfer::targets::muse_glimmer_30b::detail {

struct TextConfig {
    static constexpr int hidden       = 6656;
    static constexpr int layers       = 52;
    static constexpr int intermediate = 19968;

    // 输出行/采样域 (转换/artifact 阶段可再按内核 padding 调整).
    static constexpr int output_rows  = 202048;
    static constexpr int token_domain = output_rows;

    // 纯 softmax 族: 无 GDN/卷积/MTP. 槽位保留 0 (共享 ModelConfig 表面).
    static constexpr int gdn_conv_kernel      = 0;
    static constexpr int gdn_conv_state_width = 0;
    static constexpr int gdn_key_heads        = 0;
    static constexpr int gdn_key_head_dim     = 0;
    static constexpr int gdn_value_heads      = 0;
    static constexpr int gdn_value_head_dim   = 0;

    static constexpr int query_heads = 32;
    static constexpr int kv_heads    = 2;
    static constexpr int head_dim    = 128;
    static constexpr int rotary_dim  = 128;

    static constexpr float rms_epsilon      = 1e-05F;
    static constexpr float post_norm_eps    = 1e-08F;
    static constexpr float rope_theta       = 500000.0F;

    // 架构旋钮 (自动适配, 参考实现推导语义).
    static constexpr int   sliding_window        = 2048;
    static constexpr float qk_scale_factor       = 3.87F;
    static constexpr float final_logit_softcapping = 20.0F;

    static constexpr int key_dim               = gdn_key_heads * gdn_key_head_dim;
    static constexpr int value_dim             = gdn_value_heads * gdn_value_head_dim;
    static constexpr int convolution_dim       = 2 * key_dim + value_dim;
    static constexpr int query_size            = query_heads * head_dim;
    static constexpr int kv_size               = kv_heads * head_dim;
    static constexpr int query_projection_rows = 2 * query_size;

    static constexpr int mtp_layers               = 0;
    static constexpr int mtp_input_rows           = 0;
    static constexpr int mtp_attention_input_rows = 0;
    static constexpr int mtp_mlp_gate_up_rows     = 0;

    // 逐层口味表: 0 = full, 1 = swa (sliding window). 全部层均为 softmax 注意力;
    // gdn 层数为 0 -> 共享 run_layers 的 gdn 分支恒不进入.
    static constexpr std::array<int, 52> layer_kind{1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0};
    // 逐层 rope theta; 0 = NoPE (整层无位置编码, 引用推导语义:
    //   position_embeddings if layer_rope_theta[i] else None).
    static constexpr std::array<float, 52> layer_rope_theta{500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F, 500000.0F, 500000.0F, 500000.0F, 0.0F};
    static constexpr std::array<int, 13> kFullLayers{3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51};

    [[nodiscard]] static constexpr bool is_full_attention(int layer) {
        return layer_kind[static_cast<std::size_t>(layer)] == 0;
    }
    [[nodiscard]] static constexpr bool is_swa_attention(int layer) {
        return layer_kind[static_cast<std::size_t>(layer)] == 1;
    }
    [[nodiscard]] static constexpr bool qk_norm_enabled() { return true; }
    [[nodiscard]] static constexpr bool per_layer_scalar() { return false; }
    [[nodiscard]] static constexpr bool final_logit_softcapping_enabled() {
        return final_logit_softcapping > 0.0F;
    }
    [[nodiscard]] static constexpr float output_multiplier() { return 0.19611613513818404F; }
    [[nodiscard]] static constexpr int full_attention_layers() { return 13; }
    [[nodiscard]] static constexpr int swa_attention_layers() { return 39; }
    [[nodiscard]] static constexpr int gdn_layers() { return 0; }
    [[nodiscard]] static constexpr int swa_attention_index(int layer) {
        int n = 0;
        for (int i = 0; i < layer; ++i) { n += is_swa_attention(i) ? 1 : 0; }
        return n;
    }
    [[nodiscard]] static constexpr int full_attention_index(int layer) {
        int n = 0;
        for (int i = 0; i < layer; ++i) { n += is_full_attention(i) ? 1 : 0; }
        return n;
    }
    [[nodiscard]] static constexpr int gdn_index(int) { return 0; }
    [[nodiscard]] static constexpr int layer_of_full_index(int fidx) {
        return kFullLayers[static_cast<std::size_t>(fidx)];
    }
    [[nodiscard]] static constexpr float rope_theta_at(int layer) {
        return layer_rope_theta[static_cast<std::size_t>(layer)];
    }
};

static_assert(TextConfig::full_attention_layers() == 13);
static_assert(TextConfig::swa_attention_layers() == 39);
static_assert(TextConfig::gdn_layers() == 0);
static_assert(TextConfig::layer_kind.size() == 52);
static_assert(TextConfig::layer_rope_theta.size() == 52);
// full 层位 bijection: layer_of_full_index(fidx) 逐一命中 full.
static_assert([] {
    for (int f = 0; f < TextConfig::full_attention_layers(); ++f) {
        if (!TextConfig::is_full_attention(TextConfig::layer_of_full_index(f))) {
            return false;
        }
    }
    return true;
}());
// NoPE 语义门: full 层 theta==0, swa 层 theta>0 (参考代码推导).
static_assert([] {
    for (int l = 0; l < TextConfig::layers; ++l) {
        const bool no_pe = TextConfig::rope_theta_at(l) == 0.0F;
        if (no_pe != TextConfig::is_full_attention(l)) { return false; }
    }
    return true;
}());

inline constexpr float kAttentionScale = 0.34206290539899237F;
inline constexpr std::uint32_t kNativeContext = 131072;

} // namespace ninfer::targets::muse_glimmer_30b::detail
