#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_target.py — ARCHKIT 生成器 v1。

输入 arch-spec.json, 输出:
  1. <out>/config.h       — TextConfig constexpr (自包含, 可直接 g++ 语法检查)
  2. <out>/manifest.json  — 机器可读接入清单 (GUI 白名单/registry/转换器输入)

清单文件名与读者一致: tools/gui/model_import.find_manifest 找的就是 manifest.json
(本生成器原来写 arch_manifest.json, 于是缺口报告永远找不到它写的清单)。
本生成器没有算子目录, 所以清单里写 `"gaps": null` + `"gaps_measured": false` ——
"未测量", 不是"没有缺口"; 报真实缺口的是 adapt.py。

v1 只做"确定性翻译" (spec -> 常量头 + 清单), 不生成需要对齐 runtime 精确
API 的 bindings/package/recipe 代码 —— 那部分等接入首个目标时对着真实
qwen3_6 变体抄写, 并把差异回填到本生成器 (设计见 _ARCHKIT.md 第 6 节)。

用法:
  python gen_target.py <spec.json> [--out <dir>]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import arch_spec  # noqa: E402

#: The file name the reader looks for. One constant, because the writer/reader pair
#: drifting apart is exactly what hid this generator's manifest from the gap report.
MANIFEST_NAME = "manifest.json"


def fmt_int(v) -> str:
    """把数值格式化成 C++ 可读字面量 (带千分位下划线, 便于核对)。"""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return f"{v:_d}".replace("_", "")
    if isinstance(v, float):
        return repr(v)
    return str(v)


def norm_layer_kind(t: str) -> str:
    """HF 层型命名 -> 统一口味: full_attention/full -> full;
    sliding_attention -> swa; 其余 (linear/gdn) -> gdn。"""
    t = (t or "").lower()
    if "full" in t:
        return "full"
    if "sliding" in t:
        return "swa"
    return "gdn"


def gen_config_h(spec: dict) -> str:
    g = spec["geometry"]
    o = []
    o.append("// Generated by tools/archkit/gen_target.py — DO NOT EDIT BY HAND.")
    o.append("// spec: %s (%s)" % (spec["model_id"], spec.get("notes", "")))
    o.append("#pragma once")
    o.append("")
    o.append("namespace ninfer::targets::%s::detail {" % spec["model_id"].replace("-", "_"))
    o.append("")
    o.append("// 主模型几何 (constexpr, 全部来自 arch-spec) ")
    o.append("struct TextConfig {")
    for spec_name, cpp_name in {"hidden": "hidden", "layers": "layers",
                                "query_heads": "query_heads", "kv_heads": "kv_heads",
                                "head_dim": "head_dim", "vocab": "vocab",
                                "max_ctx": "max_ctx"}.items():
        if spec_name in g:
            o.append("    static constexpr int %s = %s;" % (cpp_name, fmt_int(g[spec_name])))
    # 混合注意力层型: full / swa / gdn 交替 (HF layer_types 或 interval)
    types = spec.get("layer_types") or []
    n_full = sum(1 for t in types if norm_layer_kind(t) == "full")
    n_swa = sum(1 for t in types if norm_layer_kind(t) == "swa")
    o.append("    static constexpr int full_attention_layers() { return %d; }" % n_full)
    o.append("    static constexpr int swa_layers() { return %d; }" % n_swa)
    o.append("    static constexpr int gdn_layers() { return %d; }"
             % max(0, g.get("layers", 0) - n_full - n_swa))
    o.append("};")
    o.append("")
    # MoE
    if "moe" in spec:
        m = spec["moe"]
        o.append("// MoE (每 token 路由 n 个专家) ")
        o.append("struct MoEConfig {")
        o.append("    static constexpr bool enabled          = true;")
        for k in ("num_experts", "num_experts_per_tok", "moe_intermediate_size",
                  "shared_expert_intermediate_size"):
            if k in m:
                o.append("    static constexpr int %s = %s;" % (k, fmt_int(m[k])))
        o.append("};")
        o.append("")
    # GDN (线性注意力层)
    if "gdn" in spec:
        d = spec["gdn"]
        o.append("// GDN 线性注意力层参数 ")
        o.append("struct GDNConfig {")
        for k in ("linear_conv_kernel_dim", "linear_key_head_dim",
                  "linear_num_key_heads", "linear_num_value_heads",
                  "linear_value_head_dim"):
            if k in d:
                o.append("    static constexpr int %s = %s;" % (k, fmt_int(d[k])))
        if "output_gate_type" in d:
            o.append('    static constexpr const char* output_gate_type = "%s";'
                     % d["output_gate_type"])
        o.append("};")
        o.append("")
    # PLE ngram (SSD 外挂候选)
    if "ple" in spec:
        p = spec["ple"]
        o.append("// PLE n-gram 查表 (mmap SSD 友好: 行寻址只读) ")
        o.append("struct PLEConfig {")
        for k in ("ngram_size", "heads_per_ngram", "ngram_vocab_size_base",
                  "ple_conv_kernel_size", "ple_embed_dim"):
            if k in p:
                o.append("    static constexpr int %s = %s;" % (k, fmt_int(p[k])))
        if "ple_layer_ids" in p:
            o.append("    static constexpr int ple_layer_ids[] = {%s};"
                     % ", ".join(str(x) for x in p["ple_layer_ids"]))
        o.append("};")
        o.append("")
    # MTP
    if "mtp" in spec:
        m = spec["mtp"]
        o.append("// MTP 草稿层 ")
        o.append("struct MtpConfig {")
        o.append("    static constexpr int mtp_layers = %d;"
                 % int(m.get("mtp_num_hidden_layers", 1)))
        o.append("    static constexpr bool dedicated_embeddings = %s;"
                 % fmt_int(bool(m.get("mtp_use_dedicated_embeddings", False))))
        o.append("};")
        o.append("")
    o.append("} // namespace ninfer::targets::%s::detail" % spec["model_id"].replace("-", "_"))
    o.append("")
    return "\n".join(o)


def gen_manifest(spec: dict) -> dict:
    """机器可读清单: GUI 导入向导白名单 + 转换器/registry 输入。

    `gaps` 故意写成 None。本生成器没有算子目录, 报不出这个家族在引擎侧缺什么;
    而"干脆不写这个字段"与"什么也不缺"在读者眼里读起来是一样的。缺口报告
    (tools/gui/model_import.manifest_gap_state / import_gap_report) 现在把
    "缺字段 / 显式 null / 非列表 / 自己声明 gaps_measured:false" 一律读成
    UNMEASURED, 写 `"gaps": null` + `gaps_measured: False` 是把这件事说明白,
    而不是靠读者去猜。报真实缺口的是 tools/archkit/adapt.py。

    `gui_hint` 里不再有 `"supported": True`。它以前是一句关于"引擎能跑这个家族"
    的断言, 而树里**没有任何读取方**, 也没有任何检查 —— 断言错了也不会响。
    现在替换成 `spec_extracted` / `engine_supported` 两个字段, 由
    tools/gui/model_import.gui_hint_claims() 读出来放进 UNKNOWN 报告里, 且
    `engine_supported` 的值是 None(未验证) 而不是 True: 本生成器从来没检查过
    引擎能不能吃这个家族, 所以它没有资格说能。
    """
    return {
        "model_id": spec["model_id"],
        "family": spec.get("family", ""),
        "hf": spec.get("hf", {}),
        "geometry": spec.get("geometry", {}),
        "has_moe": "moe" in spec,
        "has_gdn": "gdn" in spec,
        "has_ple": "ple" in spec,
        "has_mtp": "mtp" in spec,
        "layer_types": [norm_layer_kind(t) for t in spec.get("layer_types", [])],
        "gaps": None,
        "gaps_measured": False,
        "gaps_source": ("none: gen_target.py v1 has no operator catalogue "
                        "(tools/archkit/adapt.py reports real gaps)"),
        "verified_against_engine": False,
        "gui_hint": {
            "spec_extracted": True,
            "engine_supported": None,
            "import_note": ("该家族可被本生成器翻译 (确定性映射); "
                            "引擎是否支持该家族**未验证** —— 见 tools/archkit/adapt.py "
                            "的缺口报告"),
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("spec", help="arch-spec.json")
    ap.add_argument("--out", required=True, help="输出目录 (生成 config.h + manifest)")
    args = ap.parse_args()

    spec = arch_spec.load_spec(args.spec)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "config.h").write_text(gen_config_h(spec), encoding="utf-8")
    # MANIFEST_NAME is the name the reader (tools/gui/model_import.find_manifest)
    # looks for. This generator used to write arch_manifest.json, which no reader
    # looked at (it is still accepted as a legacy name), so the gap report could
    # never find the manifest it had written.
    with open(out_dir / MANIFEST_NAME, "w", encoding="utf-8") as f:
        json.dump(gen_manifest(spec), f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("generated into %s:" % out_dir)
    print("  config.h       (TextConfig/MoE/GDN/PLE/MTP constexpr)")
    print("  %s (GUI 白名单 + registry/转换器输入; gaps 未测量)" % MANIFEST_NAME)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
